# Generated by Django 5.1.1 on 2024-10-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_annotation_text_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='annotations',
        ),
        migrations.AddField(
            model_name='annotation',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.text'),
        ),
    ]
