# Generated by Django 5.1.1 on 2024-10-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_text_annotations_annotation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.text'),
        ),
    ]
