# Generated by Django 5.1.1 on 2024-10-01 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_annotation_text_alter_annotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='selected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
