name: github-actions
on:
  push:
    branches:
      - test/cypress-unit
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Setup Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt

      - name: Apply backend migrations
        working-directory: ./backend
        run: |
          python manage.py migrate

      - name: Run backend tests
        working-directory: ./backend
        run: |
          python manage.py test

      - name: Run backend linter
        working-directory: ./backend
        run: |
          flake8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm ci

      - name: Run Cypress tests
        working-directory: ./frontend
        run: |
          npx cypress run
